name: ci-workflow-first-handson

on:
  push:
    branches:
      - main
      - feature-1
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim